site_name: Magflow
site_url: https://github.com.lewinkoon.io/magflow
site_author: Lewin
copyright: Copyright &copy; 2025 Lewin

# Navigation structure
nav:
  - Home: index.md
  - Setup: setup.md
  - Usage: usage.md


theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    # - navigation.tabs
    - navigation.footer
    - toc.follow
    - content.code.copy
    - content.code.select
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


# Repository configuration
repo_url: https://github.com/lewinkoon/magflow
repo_name: GitHub

# Output directory
site_dir: site

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/lewinkoon

markdown_extensions:
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
