[project]
name = "magflow"
version = "0.1.0"
description = "Visualize velocity image series from a phase contrast magnetic resonance imaging study as three-dimensional vector field."
readme = "readme.md"
requires-python = ">=3.12"
dependencies = [
    "pydicom>=3.0.1",
    "streamlit>=1.41.1",
    "typer>=0.15.1",
    "vtk>=9.4.1",
]

[project.scripts]
magflow = "magflow.cli:app"

[dependency-groups]
dev = ["mkdocs>=1.6.1", "mkdocs-material>=9.5.49"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
