[project]
name = "magflow"
version = "0.1.0"
description = "Visualize velocity image series from a phase contrast magnetic resonance imaging study as three-dimensional vector field."
readme = "readme.md"
requires-python = ">=3.12"
dependencies = ["pydicom", "streamlit", "typer", "vtk"]

[project.scripts]
magflow = "magflow.cli:app"

[dependency-groups]
dev = ["mkdocs", "mkdocs-material"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
